# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ant/Development/GitProjects/fixtr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ant/Development/GitProjects/fixtr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.6.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ant/Development/GitProjects/fixtr/CMakeFiles /Users/ant/Development/GitProjects/fixtr/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ant/Development/GitProjects/fixtr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fixspec

# Build rule for target.
fixspec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fixspec
.PHONY : fixspec

# fast build rule for target.
fixspec/fast:
	$(MAKE) -f CMakeFiles/fixspec.dir/build.make CMakeFiles/fixspec.dir/build
.PHONY : fixspec/fast

#=============================================================================
# Target rules for targets named fixtr

# Build rule for target.
fixtr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fixtr
.PHONY : fixtr

# fast build rule for target.
fixtr/fast:
	$(MAKE) -f CMakeFiles/fixtr.dir/build.make CMakeFiles/fixtr.dir/build
.PHONY : fixtr/fast

#=============================================================================
# Target rules for targets named fixcore

# Build rule for target.
fixcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fixcore
.PHONY : fixcore

# fast build rule for target.
fixcore/fast:
	$(MAKE) -f CMakeFiles/fixcore.dir/build.make CMakeFiles/fixcore.dir/build
.PHONY : fixcore/fast

fixcore.o: fixcore.cpp.o

.PHONY : fixcore.o

# target to build an object file
fixcore.cpp.o:
	$(MAKE) -f CMakeFiles/fixcore.dir/build.make CMakeFiles/fixcore.dir/fixcore.cpp.o
.PHONY : fixcore.cpp.o

fixcore.i: fixcore.cpp.i

.PHONY : fixcore.i

# target to preprocess a source file
fixcore.cpp.i:
	$(MAKE) -f CMakeFiles/fixcore.dir/build.make CMakeFiles/fixcore.dir/fixcore.cpp.i
.PHONY : fixcore.cpp.i

fixcore.s: fixcore.cpp.s

.PHONY : fixcore.s

# target to generate assembly for a file
fixcore.cpp.s:
	$(MAKE) -f CMakeFiles/fixcore.dir/build.make CMakeFiles/fixcore.dir/fixcore.cpp.s
.PHONY : fixcore.cpp.s

fixspec.o: fixspec.cpp.o

.PHONY : fixspec.o

# target to build an object file
fixspec.cpp.o:
	$(MAKE) -f CMakeFiles/fixspec.dir/build.make CMakeFiles/fixspec.dir/fixspec.cpp.o
.PHONY : fixspec.cpp.o

fixspec.i: fixspec.cpp.i

.PHONY : fixspec.i

# target to preprocess a source file
fixspec.cpp.i:
	$(MAKE) -f CMakeFiles/fixspec.dir/build.make CMakeFiles/fixspec.dir/fixspec.cpp.i
.PHONY : fixspec.cpp.i

fixspec.s: fixspec.cpp.s

.PHONY : fixspec.s

# target to generate assembly for a file
fixspec.cpp.s:
	$(MAKE) -f CMakeFiles/fixspec.dir/build.make CMakeFiles/fixspec.dir/fixspec.cpp.s
.PHONY : fixspec.cpp.s

fixtr.o: fixtr.cpp.o

.PHONY : fixtr.o

# target to build an object file
fixtr.cpp.o:
	$(MAKE) -f CMakeFiles/fixtr.dir/build.make CMakeFiles/fixtr.dir/fixtr.cpp.o
.PHONY : fixtr.cpp.o

fixtr.i: fixtr.cpp.i

.PHONY : fixtr.i

# target to preprocess a source file
fixtr.cpp.i:
	$(MAKE) -f CMakeFiles/fixtr.dir/build.make CMakeFiles/fixtr.dir/fixtr.cpp.i
.PHONY : fixtr.cpp.i

fixtr.s: fixtr.cpp.s

.PHONY : fixtr.s

# target to generate assembly for a file
fixtr.cpp.s:
	$(MAKE) -f CMakeFiles/fixtr.dir/build.make CMakeFiles/fixtr.dir/fixtr.cpp.s
.PHONY : fixtr.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... install/strip"
	@echo "... fixspec"
	@echo "... list_install_components"
	@echo "... fixtr"
	@echo "... install/local"
	@echo "... fixcore"
	@echo "... fixcore.o"
	@echo "... fixcore.i"
	@echo "... fixcore.s"
	@echo "... fixspec.o"
	@echo "... fixspec.i"
	@echo "... fixspec.s"
	@echo "... fixtr.o"
	@echo "... fixtr.i"
	@echo "... fixtr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

